### PR TITLE
Added support for julia

### PR DESCRIPTION
**Pull request by omazapa**
small change to support Julia, requested by @peremato

### CODE REVIEW

**Comment by diocas** [comment]
Does this break with stacks that don't have the julia kernel?  ( for other kernels we check if they exist first).
We still need some manual configs for it, right? Or did the librarians manage to make it work ootb?

**Comment by peremato** [comment]
> Does this break with stacks that don't have the julia kernel? ( for other kernels we check if they exist first).
> We still need some manual configs for it, right? Or did the librarians manage to make it work ootb?

This change just copies the julia kernel to the running place without modify anything. We (from the LCG stack) will make sure that kernel speck is correct. In this way we make sure that the same installation of julia/iIJulia works in SWAN and lxplus.
Can it be merged to test it asap?

**Review by diocas — APPROVED** [review]

**Comment by diocas** [comment]
@peremato @omazapa the image is available in qa001 (the next time we can test without the need to merge changes in master, especially if they were not tested)

**Comment by peremato** [comment]
@diocas what is `qa001`? Cannot start a SWAN session in https://qa001.cern.ch

**Comment by peremato** [comment]
Is in production? I do not see it in https://swan002.cern.ch/

**Comment by etejedor** [comment]
@peremato it is https://swan-qa002.cern.ch and it is only accessible from inside the CERN network.

**Pull request merged**
