### PR TITLE
Use python -s to start jupyterhub-singleuser

### LINKED ISSUE #48: Path configuration files(.pth) are still loaded from user site-packages for jupyterhub.singleuser process
Python import machinery, has the [site](https://docs.python.org/3/library/site.html) module which configures where to look for packages. The module on import, also loads any `.pth` files in the default paths to `sys.path`.

Due to the way we remove the user site-packages by modifying `sys.path` [here](https://github.com/swan-cern/systemuser-image/blob/aa3827cd13bc7eed4a81af345ecc997bb1120c36/executables/jupyterhub-singleuser#L5) after interpreter startup, path configuration files are still loaded from user site-packages. The `site` module is auto-imported when the interpreter starts, and reads `.pth` files before we remove user site-packages directory from `sys.path`

## Impact
Users who have `.pth` files in their CERNBox, i.e `~/.local/**/site-packages` , can break the dependency resolution for notebook server and fail to spawn a session. However it's not clear how these files are added or if installing specific packages triggers this.

## Potential Solution

- Run jupyterhub-singleuser using the python `-s` [option](https://docs.python.org/3/using/cmdline.html#cmdoption-s) only for the notebook server (not kernel processes) which does not load from the user site-packages. (Not tested)

Support Ticket: [INC2957704](https://cern.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsysparm_query%3Dnumber%3DINC2957704)

### PR DESCRIPTION
**Pull request by krishnan-r**
https://docs.python.org/3/using/cmdline.html#cmdoption-s

Fixes #48

### CODE REVIEW

**Review by rccern — APPROVED** [review]

**Comment by diocas** [comment]
What if we removed this file completely and changed the way we start the process in systemuser.sh instead? Might be more understandable that way and with less stuff to maintain.

**Comment by krishnan-r** [comment]
@diocas That's a good idea, I have updated the PR, can you check if this looks alright

**Review by diocas — DISMISSED** [review]
Looks good! Can we merge?

**Comment by rccern** [comment]
We only have one version of python3 in the image, so we can just run /usr/local/bin/python3 . Otherwise we need to change this file every time we change python3 minor version in the notebook image

**Review by rccern — APPROVED** [review]

**Review by diocas — APPROVED** [review]

**Pull request merged**
